version: '3.0'

services:
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cashforce_v3
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - my_network
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3399:3399"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/cashforce_v3
    depends_on:
      - db
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:

volumes:
  db_data: