version: '3.0'

services:
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cashforce_v3
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - my_network
  
networks:
  my_network:

volumes:
  db_data:
